name: ğŸ·ï¸ Versioning

on:
  push:
    branches: [development]

jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # Fetch all history
          token: ${{ secrets.PAT }}

      - name: ğŸ”‘ Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: â¬‡ï¸ Download cocogitto
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cocogitto

      - name: ğŸ·ï¸ Versioning
        run: cog bump --auto --skip-ci

      - name: ğŸš€ Push
        run: git push --follow-tags